package sage.integration.commands

/**
  * The acknowledged command-coverage partition. `skipped` is deliberate-never with reasons; `todo` is the honest gap, regenerable by
  * diffing a live server against the implemented samples. The coverage spec fails on any unacknowledged drift.
  */
object Coverage {

  val skipped: Map[String, String] = Map(
    "GETSET"           -> "deprecated: SET with setGet subsumes it",
    "SETNX"            -> "deprecated: SET with SetCondition.IfNotExists",
    "SETEX"            -> "deprecated: SET with SetExpiry.In",
    "PSETEX"           -> "deprecated: SET with SetExpiry.In",
    "SUBSTR"           -> "deprecated: GETRANGE",
    "HMSET"            -> "deprecated: HSET takes multiple field/value pairs",
    "RPOPLPUSH"        -> "deprecated: LMOVE",
    "ZRANGEBYSCORE"    -> "deprecated: ZRANGE with ByScore",
    "ZRANGEBYLEX"      -> "deprecated: ZRANGE with ByLex",
    "ZREVRANGE"        -> "deprecated: ZRANGE with ByRank and rev",
    "ZREVRANGEBYSCORE" -> "deprecated: ZRANGE with ByScore and rev",
    "ZREVRANGEBYLEX"   -> "deprecated: ZRANGE with ByLex and rev",
    "PUBSUB CHANNELS"  -> "implemented as PUBSUB; the subcommand is an argument, not a separate Command name",
    "PUBSUB NUMSUB"    -> "implemented as PUBSUB; the subcommand is an argument, not a separate Command name",
    "PUBSUB NUMPAT"    -> "implemented as PUBSUB; the subcommand is an argument, not a separate Command name",
    "SUBSCRIBE"        -> "delivered via the subscribe stream API, not a runnable command",
    "PSUBSCRIBE"       -> "delivered via the pSubscribe stream API, not a runnable command",
    "UNSUBSCRIBE"      -> "sent by the subscribe stream's scope closure, not a runnable command",
    "PUNSUBSCRIBE"     -> "sent by the pSubscribe stream's scope closure, not a runnable command",
    "MULTI"            -> "driven by the transaction scope API, not a runnable command",
    "EXEC"             -> "driven by the transaction scope API, not a runnable command",
    "WATCH"            -> "driven by the transaction scope API, not a runnable command",
    "UNWATCH"          -> "driven by the transaction scope API, not a runnable command",
    "ASKING"           -> "issued by cluster ASK-redirect handling, not a runnable command",
    "CLUSTER SLOTS"    -> "issued by cluster topology discovery, not a runnable command"
  )

  val todo: Set[String] = Set(
    "ACL",
    "ACL CAT",
    "ACL DELUSER",
    "ACL DRYRUN",
    "ACL GENPASS",
    "ACL GETUSER",
    "ACL HELP",
    "ACL LIST",
    "ACL LOAD",
    "ACL LOG",
    "ACL SAVE",
    "ACL SETUSER",
    "ACL USERS",
    "ACL WHOAMI",
    "ARCOUNT",
    "ARDEL",
    "ARDELRANGE",
    "ARGET",
    "ARGETRANGE",
    "ARGREP",
    "ARINFO",
    "ARINSERT",
    "ARLASTITEMS",
    "ARLEN",
    "ARMGET",
    "ARMSET",
    "ARNEXT",
    "AROP",
    "ARRING",
    "ARSCAN",
    "ARSEEK",
    "ARSET",
    "AUTH",
    "BGREWRITEAOF",
    "BGSAVE",
    "BITCOUNT",
    "BITFIELD",
    "BITFIELD_RO",
    "BITOP",
    "BITPOS",
    "BRPOPLPUSH",
    "CLIENT",
    "CLIENT CACHING",
    "CLIENT CAPA",
    "CLIENT GETNAME",
    "CLIENT GETREDIR",
    "CLIENT HELP",
    "CLIENT ID",
    "CLIENT IMPORT-SOURCE",
    "CLIENT INFO",
    "CLIENT KILL",
    "CLIENT LIST",
    "CLIENT NO-EVICT",
    "CLIENT NO-TOUCH",
    "CLIENT PAUSE",
    "CLIENT REPLY",
    "CLIENT SETINFO",
    "CLIENT SETNAME",
    "CLIENT TRACKING",
    "CLIENT TRACKINGINFO",
    "CLIENT UNBLOCK",
    "CLIENT UNPAUSE",
    "CLUSTER",
    "CLUSTER ADDSLOTS",
    "CLUSTER ADDSLOTSRANGE",
    "CLUSTER BUMPEPOCH",
    "CLUSTER COUNT-FAILURE-REPORTS",
    "CLUSTER COUNTKEYSINSLOT",
    "CLUSTER DELSLOTS",
    "CLUSTER DELSLOTSRANGE",
    "CLUSTER FAILOVER",
    "CLUSTER FLUSHSLOTS",
    "CLUSTER FORGET",
    "CLUSTER GETKEYSINSLOT",
    "CLUSTER HELP",
    "CLUSTER INFO",
    "CLUSTER KEYSLOT",
    "CLUSTER LINKS",
    "CLUSTER MEET",
    "CLUSTER MIGRATION",
    "CLUSTER MYID",
    "CLUSTER MYSHARDID",
    "CLUSTER NODES",
    "CLUSTER REPLICAS",
    "CLUSTER REPLICATE",
    "CLUSTER RESET",
    "CLUSTER SAVECONFIG",
    "CLUSTER SET-CONFIG-EPOCH",
    "CLUSTER SETSLOT",
    "CLUSTER SHARDS",
    "CLUSTER SLAVES",
    "CLUSTER SLOT-STATS",
    "CLUSTER SYNCSLOTS",
    "COMMAND",
    "COMMAND COUNT",
    "COMMAND DOCS",
    "COMMAND GETKEYS",
    "COMMAND GETKEYSANDFLAGS",
    "COMMAND HELP",
    "COMMAND INFO",
    "COMMAND LIST",
    "COMMANDLOG",
    "COMMANDLOG GET",
    "COMMANDLOG HELP",
    "COMMANDLOG LEN",
    "COMMANDLOG RESET",
    "CONFIG",
    "CONFIG GET",
    "CONFIG HELP",
    "CONFIG RESETSTAT",
    "CONFIG REWRITE",
    "CONFIG SET",
    "DBSIZE",
    "DEBUG",
    "DELEX",
    "DIGEST",
    "DISCARD",
    "DUMP",
    "ECHO",
    "EVAL",
    "EVAL_RO",
    "EVALSHA",
    "EVALSHA_RO",
    "FAILOVER",
    "FCALL",
    "FCALL_RO",
    "FLUSHALL",
    "FLUSHDB",
    "FUNCTION",
    "FUNCTION DELETE",
    "FUNCTION DUMP",
    "FUNCTION FLUSH",
    "FUNCTION HELP",
    "FUNCTION KILL",
    "FUNCTION LIST",
    "FUNCTION LOAD",
    "FUNCTION RESTORE",
    "FUNCTION STATS",
    "GEOADD",
    "GEODIST",
    "GEOHASH",
    "GEOPOS",
    "GEORADIUS",
    "GEORADIUS_RO",
    "GEORADIUSBYMEMBER",
    "GEORADIUSBYMEMBER_RO",
    "GEOSEARCH",
    "GEOSEARCHSTORE",
    "GETBIT",
    "HEXPIRE",
    "HEXPIREAT",
    "HEXPIRETIME",
    "HGETDEL",
    "HGETEX",
    "HOTKEYS",
    "HOTKEYS GET",
    "HOTKEYS HELP",
    "HOTKEYS RESET",
    "HOTKEYS START",
    "HOTKEYS STOP",
    "HPERSIST",
    "HPEXPIRE",
    "HPEXPIREAT",
    "HPEXPIRETIME",
    "HPTTL",
    "HSETEX",
    "HTTL",
    "INCREX",
    "INFO",
    "LASTSAVE",
    "LATENCY",
    "LATENCY DOCTOR",
    "LATENCY GRAPH",
    "LATENCY HELP",
    "LATENCY HISTOGRAM",
    "LATENCY HISTORY",
    "LATENCY LATEST",
    "LATENCY RESET",
    "LCS",
    "LOLWUT",
    "MEMORY",
    "MEMORY DOCTOR",
    "MEMORY HELP",
    "MEMORY MALLOC-STATS",
    "MEMORY PURGE",
    "MEMORY STATS",
    "MEMORY USAGE",
    "MIGRATE",
    "MODULE",
    "MODULE HELP",
    "MODULE LIST",
    "MODULE LOAD",
    "MODULE LOADEX",
    "MODULE UNLOAD",
    "MONITOR",
    "MOVE",
    "MSETEX",
    "OBJECT",
    "OBJECT ENCODING",
    "OBJECT FREQ",
    "OBJECT HELP",
    "OBJECT IDLETIME",
    "OBJECT REFCOUNT",
    "PFADD",
    "PFCOUNT",
    "PFDEBUG",
    "PFMERGE",
    "PFSELFTEST",
    "PSYNC",
    "PUBSUB HELP",
    "PUBSUB SHARDCHANNELS",
    "PUBSUB SHARDNUMSUB",
    "QUIT",
    "READONLY",
    "READWRITE",
    "REPLCONF",
    "REPLICAOF",
    "RESET",
    "RESTORE",
    "RESTORE-ASKING",
    "ROLE",
    "SAVE",
    "SCRIPT",
    "SCRIPT DEBUG",
    "SCRIPT EXISTS",
    "SCRIPT FLUSH",
    "SCRIPT HELP",
    "SCRIPT KILL",
    "SCRIPT LOAD",
    "SCRIPT SHOW",
    "SELECT",
    "SETBIT",
    "SHUTDOWN",
    "SLAVEOF",
    "SLOWLOG",
    "SLOWLOG GET",
    "SLOWLOG HELP",
    "SLOWLOG LEN",
    "SLOWLOG RESET",
    "SORT",
    "SORT_RO",
    "SPUBLISH",
    "SSUBSCRIBE",
    "SUNSUBSCRIBE",
    "SWAPDB",
    "SYNC",
    "TIME",
    "TRIMSLOTS",
    "WAIT",
    "WAITAOF",
    "XACK",
    "XACKDEL",
    "XADD",
    "XAUTOCLAIM",
    "XCFGSET",
    "XCLAIM",
    "XDEL",
    "XDELEX",
    "XGROUP",
    "XGROUP CREATE",
    "XGROUP CREATECONSUMER",
    "XGROUP DELCONSUMER",
    "XGROUP DESTROY",
    "XGROUP HELP",
    "XGROUP SETID",
    "XIDMPRECORD",
    "XINFO",
    "XINFO CONSUMERS",
    "XINFO GROUPS",
    "XINFO HELP",
    "XINFO STREAM",
    "XLEN",
    "XNACK",
    "XPENDING",
    "XRANGE",
    "XREAD",
    "XREADGROUP",
    "XREVRANGE",
    "XSETID",
    "XTRIM"
  )
}
